
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_cars'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_cars'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  +schema: false  # Prevent schema name concatenation
  dbt_cars: # Sử dụng tên project của bạn ở đây
    # ===== Staging layer =====
    staging:
      +schema: staging
      # ---- Filter group ----
      stg_filter_data_cols:
        +meta:
          dagster:
            group: "staging_filter"

      # ---- Parse group ----
      stg_parse_price:
        +meta:
          dagster:
            group: "staging_parse"
      stg_parse_mileage:
        +meta:
          dagster:
            group: "staging_parse"
      stg_parse_date_posted:
        +meta:
          dagster:
            group: "staging_parse"
      stg_parse_engine:
        +meta:
          dagster:
            group: "staging_parse"
      stg_final_parse:
        +meta:
          dagster:
            group: "staging_parse"

      # ---- Normalize group ----
      stg_normalize_base:
        +meta:
          dagster:
            group: "staging_normalize"
      stg_normalize_body_style:
        +meta:
          dagster:
            group: "staging_normalize"
      stg_normalize_color:
        +meta:
          dagster:
            group: "staging_normalize"
      stg_normalize_drivetrain:
        +meta:
          dagster:
            group: "staging_normalize"
      stg_final_normalize:
        +meta:
          dagster:
            group: "staging_normalize"

      # ---- Handle null group ----
      stg_handle_null_brand_model:
        +meta:
          dagster:
            group: "staging_handle_null"
      stg_final_handle_null:
        +meta:
          dagster:
            group: "staging_handle_null"

      # Final output of staging (root of staging folder)
      stg_final_staging:
        +meta:
          dagster:
            group: "staging"

    # ===== Marts layer =====
    marts:
      +schema: marts # -> psql in marts schema
      +materialized: table # -> default to table materialization
      # Dimensions
      dim_car_general:
        +meta:
          dagster:
            group: "marts_dimensions"
      dim_car_details:
        +meta:
          dagster:
            group: "marts_dimensions"
      dim_car_specs:
        +meta:
          dagster:
            group: "marts_dimensions"
      dim_date:
        +meta:
          dagster:
            group: "marts_dimensions"
      # Fact
      fact_car_listing:
        +meta:
          dagster:
            group: "marts_facts"